### ISSUE TITLE
Unclear log in need

### ISSUE THREAD

**Issue by ivyfortuna** [jcabrera96/GameLinker#1]
Al iniciar la aplicación, no aparece la pantalla para iniciar sesión, ni el botón para iniciar se ve claramente. Esto hace que lo primero que vayamos a pulsar sea en añadir juego y nos salte el error de inicio de sesión.

En mi opinión, debería aparecer la pantalla de inicio de sesión nada mas abrir el programa.

**Comment by jcabrera96** [comment]
¿Verías mejor eso o que te pregunte tras pulsar en 'Añadir juego' si quieres realizar el inicio de sesión y permita llevarlo a cabo?

En cuanto a que no se ve claramente el botón para iniciar sesión, ¿Te refieres a que no sabes que está ahí al encontrarse el menú oculto, que no identificas el botón para abrir el menú lateral con dicha acción y por ende no sabes que existe o ambas?

**Comment by ivyfortuna** [comment]
Creo que lo mejor sería que si no has iniciado sesión, nada mas abrir te pida que inicies sesión.

Un poco ambas, ya que el botón de añadir juego destaca mucho por encima del de abrir el menú, pero principalmente la primera, ya que al estar el menú cerrado no se ve.

**Comment by jcabrera96** [comment]
Se han implementado las mejoras indicadas en esta incidencia con la actualización 3851d9e6477fa9174b696ac2916b70e2be752195.
