### ISSUE TITLE
El inicio de sesión de la cuenta de Microsoft no esta claro

### ISSUE THREAD

**Issue by Mishifu-cpu** [jcabrera96/GameLinker#2]
A la hora de añadir las carpetas a la biblioteca de juegos, te pide que inicies sesión en tu cuenta de Microsoft. Solo hay un botón a la izquierda así que por descarte te diriges ahí. Pero estaría mejor que estuviera más claro ya que puede dar a confusión. O en su lugar, que al darle a la carpeta de juegos y te diga que inicies sesión, que aparezca de forma automatica esa opción a modo de pregunta como: ¿Quieres iniciar sesión?.

**Comment by jcabrera96** [comment]
Tema abordado en #1. ¡Se tendrá en cuenta de cara a la próxima actualización!
